########################################################################
# Copyright (c) 1988-2015 $organization$
#
# This software is provided by the author and contributors ``as is''
# and any express or implied warranties, including, but not limited to,
# the implied warranties of merchantability and fitness for a particular
# purpose are disclaimed. In no event shall the author or contributors
# be liable for any direct, indirect, incidental, special, exemplary,
# or consequential damages (including, but not limited to, procurement
# of substitute goods or services; loss of use, data, or profits; or
# business interruption) however caused and on any theory of liability,
# whether in contract, strict liability, or tort (including negligence
# or otherwise) arising in any way out of the use of this software,
# even if advised of the possibility of such damage.
#
#   File: Makefile
#
# Author: $author$
#   Date: 12/23/2015
#
# Generic Gcc Makefile for vedere libvedere Static Library
########################################################################

#
# user c++ flags
#
libvedere_USRCXXFLAGS += \
${vedere_USRCXXFLAGS} \

#
# user defines
#
libvedere_USRDEFINES = \
${vedere_USRDEFINES} \

#
# user includes
#
libvedere_USRINCLUDES = \
${vedere_USRINCLUDES} \

#
# user libdirs
#
libvedere_USRLIBDIRS = \
${vedere_USRLIBDIRS} \

#
# C .c sources
#
libvedere_LIB_C_SOURCES = \

#
# C++ .cxx sources
#
libvedere_LIB_CXX_SOURCES = \

#
# C++ .cpp sources
#
libvedere_LIB_CPP_SOURCES += \
${VEDERE_SRC}/vedere/base/base.cpp \

#
# libs
#
libvedere_LIBS = \
-lvedere \
${vedere_LIBS} \
